version: 2.1

orbs:
  node: circleci/node@5.0.1
  heroku: circleci/heroku@2.0.0
  docker: circleci/docker@2.1.4

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Install dependencies"
          npm install
  test:
    docker: 
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests"
          npm run test


  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku stack:set container -a fathomless-hamlet-28308
            heroku container:push web -a fathomless-hamlet-28308
            heroku container:release web -a fathomless-hamlet-28308

  build-and-push:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - checkout
      - docker/login:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
      - docker/build:
          image: vincentnwa/container-assignment:latest
      - docker/push:
          image: vincentnwa/container-assignment:latest

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires: 
            - build
      - deploy:
          requires:
            - test
      - build-and-push:
          requires:
            - test